### ISSUE TITLE
A11Y: Communicate active/selected state of navigation/selection elements

### ISSUE THREAD

**Issue by trm217** [republik/plattform#129]
## Description

Links and Buttons used for the page state musst share which link/button must communicate the active state for screen readers.
There are two variants for this: 
- The A11Y-review suggested the [following approach](https://www.accessibility-developer-guide.com/examples/hiding-elements/visually/).
- Additionally we should also add the `aria-current`. See [mdn-docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current)
- (This might need some more research on how we utilise links, but in general we could automatically set `aria-current="page"` on every link that has a href that matches window.location.) 

## Todo
- [x] Comment sort- and filter-links must communicate the active state
<img width="849" alt="image" src="https://user-images.githubusercontent.com/30313631/172875948-0b45c16a-0257-4103-9227-084235a45e02.png">

- [x] The navigation must communicate the active page
<img width="849" alt="image" src="https://user-images.githubusercontent.com/30313631/172876128-667be63f-0566-483d-95cc-40c25eba117b.png">

- [x] Selected payments-option must be communicated
<img width="782" alt="image" src="https://user-images.githubusercontent.com/30313631/172876638-6ac23ecc-203b-4df0-ab59-710f5995eb54.png">
